# Generated by Django 5.2.3 on 2025-06-24 03:29

import page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(verbose_name='原始網址')),
                ('short_code', models.CharField(default=page.models.generate_unique_code, max_length=100, unique=True, verbose_name='短網址代碼')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='備註說明')),
                ('is_protected', models.BooleanField(default=False, verbose_name='是否啟用密碼保護')),
                ('password', models.CharField(blank=True, max_length=100, verbose_name='密碼')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
