# Generated by Django 5.2.3 on 2025-06-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=100, verbose_name='UTM 活動'),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='utm_content',
            field=models.CharField(blank=True, max_length=100, verbose_name='UTM 內容'),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=100, verbose_name='UTM 媒介'),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='utm_source',
            field=models.CharField(blank=True, max_length=100, verbose_name='UTM 來源'),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='utm_term',
            field=models.CharField(blank=True, max_length=100, verbose_name='UTM 關鍵字'),
        ),
    ]
