# Generated by Django 5.2.3 on 2025-06-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_shorturl_utm_campaign_shorturl_utm_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='description',
            field=models.TextField(blank=True, verbose_name='備註說明'),
        ),
    ]
