# Generated by Django 5.2.3 on 2025-06-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_alter_shorturl_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='original_url',
            field=models.URLField(max_length=500, verbose_name='原始網址'),
        ),
    ]
